---
version: '2'
services:
  postgres:
    image: postgres:10.17-alpine
    environment:
      - POSTGRES_PASSWORD=qcmiopwd
      - POSTGRES_USER=qcmio
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "log_statement=all"
    ports:
      - "5432:5432"